---
title: |
  | Sacramento River Valley 
  | Salmonid Tagging Project
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
```

```{r logos, echo=FALSE}
htmltools::img(src = knitr::image_uri("../data/NOAA logo.jpg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0px; right:0px; width:100px;')
htmltools::img(src = knitr::image_uri("../data/BureauOfReclamation.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:10px; right:110px; width:200px;')
```

<br/>


# *Hatchery-origin winter-run Chinook salmon*

## Project Status


Project has begun, see tagging details below:
```{r print table with fish release details, echo = FALSE}
setwd(paste(file.path(Sys.getenv("USERPROFILE"),"Desktop",fsep="\\"), "\\Real-time data massaging", sep = ""))

tagcodes <- read.csv("qry_HexCodes.txt", stringsAsFactors = F)
tagcodes$RelDT <- as.POSIXct(tagcodes$RelDT, format = "%m/%d/%Y %I:%M:%S %p", tz = "Etc/GMT+8")


study_tagcodes <- tagcodes[tagcodes$StudyID == "Winter_H_2018",]
release_stats <- aggregate(list(Number_fish_released = study_tagcodes$TagID_Hex),
                           by= list(Release_time = study_tagcodes$RelDT),
                           FUN = function(x) {length(unique(x))}
                           )
release_stats <- merge(release_stats,
                       aggregate(list(Release_rkm = study_tagcodes$Rel_rkm),
                           by= list(Release_time = study_tagcodes$RelDT),
                           FUN = function(x) {head(x,1)}),
                       by = c("Release_time"))

kable(release_stats)
                       

```

<br/>

## Real-time Fish Detections

```{r print table of fish detections, echo = FALSE}
setwd(paste(file.path(Sys.getenv("USERPROFILE"),"Desktop",fsep="\\"), "\\Real-time data massaging", sep = ""))

test <- read.csv("detects_Winter_H_2018.csv", stringsAsFactors = F)
if (nrow(test) == 0){
  "No detections yet"
} else {
  tag_stats <- aggregate(list(First_arrival = test$Datetime), 
                         by= list(general_location = test$general_location), FUN = min)
  tag_stats <- merge(tag_stats, 
                     aggregate(list(Fish_count = test$TagCode), 
                         by= list(general_location = detects$general_location), 
                         FUN = function(x) {length(unique(x))}), 
                     by = c("general_location"))
  
  
  kable(test)
}

```
