---
title: |
  | Sacramento River Valley 
  | Salmonid Tagging Project
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r logos, echo=FALSE}
htmltools::img(src = knitr::image_uri("../data/NOAA logo.jpg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0px; right:0px; width:100px;')
htmltools::img(src = knitr::image_uri("../data/BureauOfReclamation.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:10px; right:110px; width:200px;')
```

<br/>


# *Real-time tracking Diagnostics*

## Real-time Fish Detections

```{r print plots of fish detections, echo = FALSE}
setwd(paste(file.path(Sys.getenv("USERPROFILE"),"Desktop",fsep="\\"), "\\Real-time data massaging", sep = ""))

test <- read.csv("detects_Winter_H_2018.csv", stringsAsFactors = F)
if (nrow(test) == 0){
  "No detections yet"
} else {
  kable(test)
}

```

<br/>