---
title: |
  | Central Valley Enhanced
  | Acoustic Tagging Project
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(knitr)
```

```{r logos, echo=FALSE}
htmltools::img(src = knitr::image_uri("../data/NOAA logo.jpg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0px; right:0px; width:100px;')
htmltools::img(src = knitr::image_uri("../data/BureauOfReclamation.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:10px; right:110px; width:200px;')
```

<br/>


# *Sacramento River Green Sturgeon*

## Project Status 



Project has begun, see tagging details below:
```{r print table with fish release details, echo = FALSE}
setwd(paste(file.path(Sys.getenv("USERPROFILE"),"Desktop",fsep="\\"), "\\Real-time data massaging\\products", sep = ""))

tagcodes <- read.csv("qry_HexCodes.txt", stringsAsFactors = F)
tagcodes$RelDT <- as.POSIXct(tagcodes$RelDT, format = "%m/%d/%Y %I:%M:%S %p", tz = "Etc/GMT+8")
latest <- read.csv("latest_download.csv", stringsAsFactors = F)


study_tagcodes <- tagcodes[tagcodes$StudyID == "Juv_Green_Sturgeon_2017",]
release_stats <- aggregate(list(Number_fish_released = study_tagcodes$TagID_Hex),
                           by= list(Release_time = study_tagcodes$RelDT),
                           FUN = function(x) {length(unique(x))}
                           )
release_stats <- merge(release_stats,
                       aggregate(list(Release_rkm = study_tagcodes$Rel_rkm),
                           by= list(Release_time = study_tagcodes$RelDT),
                           FUN = function(x) {head(x,1)}),
                       by = c("Release_time"))

kable(release_stats)
                       

```

<br/>

## Real-time Fish Detections

*Data current as of `r latest`*

```{r print table of fish detections, echo = FALSE}
setwd(paste(file.path(Sys.getenv("USERPROFILE"),"Desktop",fsep="\\"), "\\Real-time data massaging\\products", sep = ""))

library(data.table)

test <- fread("detects_Juv_Green_Sturgeon_2017.csv", stringsAsFactors = FALSE)
gen_locs <- read.csv("realtime_locs.csv", stringsAsFactors = F)

tagcodes <- read.csv("qry_HexCodes.txt", stringsAsFactors = F)
tagcodes$RelDT <- as.POSIXct(tagcodes$RelDT, format = "%m/%d/%Y %I:%M:%S %p", tz = "Etc/GMT+8")

study_tagcodes <- tagcodes[tagcodes$StudyID == "Juv_Green_Sturgeon_2017",]
study_count <- nrow(study_tagcodes)

if (nrow(test) == 0){
  "No detections yet"
} else {
  test$DateTime_PST <- as.POSIXct(test$DateTime_PST, format = "%Y-%m-%d %H:%M:%S")
  tag_stats <- aggregate(list(First_arrival = test$DateTime_PST), 
                         by= list(general_location = test$general_location), FUN = min)
  tag_stats <- merge(tag_stats, 
                     aggregate(list(Fish_count = test$TagCode), 
                         by= list(general_location = test$general_location), 
                         FUN = function(x) {length(unique(x))}), 
                     by = c("general_location"))
  tag_stats$Percent_arrived <- round(tag_stats$Fish_count/study_count * 100,2)
  
  tag_stats <- merge(tag_stats, unique(gen_locs[,c("general_location", "rkm")]))
  
  tag_stats <- tag_stats[order(tag_stats$rkm, decreasing = T),]
  
  kable(tag_stats, row.names = F)
}

```